### ISSUE TITLE
Dringend 1.2 doesn't show projects cloned from git

### ISSUE THREAD

**Issue by capnslipp** [SquaredTiki/Dringend-Issues#77] opened 2014-07-26 18:27 UTC
Dringend 1.2 doesn't show a project in the main Projects view after completing the clone from git.

Steps taken:
1. Removed and re-installed Dringend from the App Store.
2. Chose “Clone git repository” from the toolbar plus button/
3. Entered `https://` repo URL and enabled “Checkout submodules”.  
   ![screenshot 2014 07 26 14 18 37](https://cloud.githubusercontent.com/assets/74679/3711893/46e59322-14f1-11e4-8949-50e8dece16d3.png)
4. Pressed “Done” button; Dringend goes through sequence of modal view title changes" “Cloning…” followed by “«filename» ✅”.  
   ![screenshot 2014 07 26 14 18 52](https://cloud.githubusercontent.com/assets/74679/3711899/b1b118ca-14f1-11e4-8723-261b462e8a77.png)  
   ![screenshot 2014 07 26 14 19 00](https://cloud.githubusercontent.com/assets/74679/3711900/b3b9bdb6-14f1-11e4-8c53-36283c3a9d5d.png)
5. Presented with a “Choose Project” prompt; chose the primary xcodeproj and tapped “Choose”.  
   ![screenshot 2014 07 26 14 23 18](https://cloud.githubusercontent.com/assets/74679/3711906/f56ee498-14f1-11e4-88fc-b021021c58bf.png)
6. No resulting project in the main Projects view.  
   ![screenshot 2014 07 26 14 24 27](https://cloud.githubusercontent.com/assets/74679/3711908/1745f4c6-14f2-11e4-9ecc-70eec87dd35f.png)
7. Quit the Dringend app, waited 5 seconds (to ensure termination by the system), and re-opened.  Still no resulting project.  
   ![screenshot 2014 07 26 14 25 11](https://cloud.githubusercontent.com/assets/74679/3711914/55a131ae-14f2-11e4-956b-aa874c8dcc11.png)
   ![screenshot 2014 07 26 14 26 14](https://cloud.githubusercontent.com/assets/74679/3711915/572d0cf0-14f2-11e4-89e3-f90108febc2c.png)

**Comment by SquaredTiki** [comment] 2014-07-26 18:32
Investigating this now.

**Comment by SquaredTiki** [comment] 2014-07-26 20:12
I have identified the root cause of this issue and rectified it. I will be submitting an update immediately for this and your previous issue (#76) and requesting it be expedited by Apple.

This issue affects only projects which are located in the root directory of the Git repository. It is possible to work around this issue by closing and quitting Dringend (from the multitasking view) when the "Choose Project" view appears. Upon re-opening the project should be there.

I apologize that this wasn't caught in testing and for the inconvenience this has caused.

**Comment by capnslipp** [comment] 2014-07-26 21:48
Okay, thanks.

**Comment by vernonstinebaker** [comment] 2014-07-30 00:59
I can confirm both the bug and the work-around you mention above works properly. 

Looking forward for the update.

**Closed as completed** 2014-08-05 12:47 UTC
Labels: bug
